apiVersion: v1
kind: Service
metadata:
  name: {{ include "stan-dask-chart.fullname" . }}-scheduler
  labels:
    {{- include "stan-dask-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: scheduler
spec:
  type: {{ .Values.daskScheduler.service.type }}
  ports:
    - name: scheduler
      port: {{ .Values.daskScheduler.service.schedulerPort }}
      targetPort: scheduler
    - name: dashboard
      port: {{ .Values.daskScheduler.service.dashboardPort }}
      targetPort: dashboard
  selector:
    {{- include "stan-dask-chart.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: scheduler
