apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "stan-dask-chart.fullname" . }}-worker
  labels:
    {{- include "stan-dask-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  replicas: {{ .Values.daskWorker.replicas }}
  selector:
    matchLabels:
      {{- include "stan-dask-chart.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: worker
  template:
    metadata:
      labels:
        {{- include "stan-dask-chart.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: worker
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "stan-dask-chart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: worker
          image: "{{ .Values.daskWorker.image.repository }}:{{ .Values.daskWorker.image.tag }}"
          imagePullPolicy: {{ .Values.daskWorker.image.pullPolicy }}
          command:
            - dask-worker
            - tcp://{{ include "stan-dask-chart.fullname" . }}-scheduler:{{ .Values.daskScheduler.service.schedulerPort }}
            - --nthreads
            - "{{ .Values.daskWorker.threadsPerWorker }}"
            - --memory-limit
            - "{{ .Values.daskWorker.memoryLimit }}"
          resources:
            {{- toYaml .Values.daskWorker.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{- with .Values.extraEnv }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.daskWorker.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.daskWorker.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.daskWorker.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
